-- 9시부터 20시 전까지 시간대별로 입양이 몇 건 발생했는지 시간대순으로 조회
-- COUNT(*) : NULL 포함하여 카운트
-- COUNT(NAME) : NULL 미포함
SELECT HOUR(DATETIME) AS HOUR, COUNT(*) AS COUNT FROM ANIMAL_OUTS 
WHERE HOUR(DATETIME) >= 9 AND HOUR(DATETIME) < 20
GROUP BY HOUR(DATETIME)
ORDER BY HOUR(DATETIME) ASC;
